name: 'Linode Machine Manager'
description: 'Create and manage Linode machines and GitHub self-hosted runners'
inputs:
  linode_token:
    description: 'Linode API token'
    required: true
  github_token:
    description: 'GitHub Token'
    required: true
  action:
    description: '"create" to create a new machine, "destroy" to remove it'
    required: true
  machine_id:
    description: 'ID of the machine to destroy'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
