name: 'Linode Machine Manager'
description: 'Create and manage Linode machines and GitHub self-hosted runners'
inputs:
  linode_token:
    description: 'Linode API token'
    required: true
  github_token:
    description: 'GitHub Token'
    required: true
  action:
    description: '"create" to create a new machine, "destroy" to remove it'
    required: true
  machine_id:
    description: 'ID of the machine to destroy'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Checkout action repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Run main script
      run: node index.js
      shell: bash
