name: 'Linode Machine Manager'
description: 'Create and manage Linode machines and GitHub self-hosted runners'
inputs:
  linode_token:
    description: 'Linode API token'
    required: true
  github_token:
    description: 'GitHub Token'
    required: true
  action:
    description: '"create" to create a new machine, "destroy" to remove it'
    required: true
  machine_id:
    description: 'ID of the machine to destroy'
    required: false
  search_phrase:
    description: 'Search phrase to find the machine to destroy'
    required: false
  runner_label:
    description: 'Base label for the self-hosted runner'
    required: false
  root_password:
    description: 'Root password for the new Linode machine'
    required: true
  machine_type:
    description: 'Type of Linode machine to create'
    required: true
  image:
    description: 'Image to use for the Linode machine'
    required: true
outputs:
  runner_label:
    description: 'Final label of the self-hosted runner'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Checkout action repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      shell: bash
      working-directory: .github/actions/linode-machine-manager

    - name: Run main script
      run: node index.js
      shell: bash
      working-directory: .github/actions/linode-machine-manager
